name: flutter_vidaplus
description: "Prejeto em flutter com firebase"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  get: ^4.7.2
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  cloud_firestore: ^5.6.8
  google_sign_in: ^6.1.6
  flutter_svg: ^2.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true

